server:
  port: 8080
  tomcat:
    max-swallow-size: -1

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://10.0.10.17:3506/flyway_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Mysql-spring.datasource.hikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1








